### PR TITLE
Fixes #4 by removing migration splitting since it breaks multiline SQL scripts.

### LINKED ISSUE #4: Unterminated dollar-quoted string at or near "$$
I had a migration script with the following:
```sql
-- this function allows us to create indexes if they don't exist
create or replace function create_index_if_not_exists (t_name text, i_name text, index_sql text) returns void as $$
declare
  full_index_name varchar;
  schema_name varchar;
begin

full_index_name = t_name || '_' || i_name;
schema_name = 'public';

if not exists (
    select 1
    from   pg_class c
    join   pg_namespace n on n.oid = c.relnamespace
    where  c.relname = full_index_name
    and    n.nspname = schema_name
    ) then

    execute 'create index ' || full_index_name || ' on ' || schema_name || '.' || t_name || ' ' || index_sql;
end if;
end
$$
language plpgsql volatile;
```

Upon running migrations I got the following error: 

```
Error executing migration: pq: unterminated dollar-quoted string at or near "$$
```

Any ideas?

### PR DESCRIPTION
**Pull request by c4milo**
Fixes #4 and it also adds clarification in documentation regarding migration identifiers.

### CODE REVIEW

File: test_migrations/test1_pg/2_create_index_function_if_not_exists_up.sql [hunk 1]
```diff
@@ -0,0 +1,23 @@
+-- this function allows us to create indexes if they don't exist
```
Comment (DavidHuie) [inline test_migrations/test1_pg/2_create_index_function_if_not_exists_up.sql]: Could you create a minimum size test case that reproduces the problem?

**Comment by DavidHuie** [comment]
Please provide a writeup on how this fixes #4. Also, make sure the commit messages reflect that information.

File: test_migrations/test1_pg/2_create_index_function_if_not_exists_up.sql (hunk 1 above)
Comment (c4milo) [inline test_migrations/test1_pg/2_create_index_function_if_not_exists_up.sql]: Sure, I can, but would that be better than a real test case?

**Comment by c4milo** [comment]
@DavidHuie what was the reasoning for having "submigrations"? https://github.com/DavidHuie/gomigrate/commit/e1d596ee1c285615cbc0d6817b689e50557ee307. That was basically the main culprit for #4.

**Comment by DavidHuie** [comment]
@c4milo I actually can't recall, so I'm in favor of removing that aspect. I *think* it was for more granular error output. Anyway, it clearly breaks scripts, so let's drop it.

File: test_migrations/test1_pg/2_create_index_function_if_not_exists_up.sql (hunk 1 above)
Comment (DavidHuie) [inline test_migrations/test1_pg/2_create_index_function_if_not_exists_up.sql]: This was mostly because I couldn't tell how the test case made the previous code fail.

**Comment by c4milo** [comment]
There you have the reason for how #4 was fixed :)
